server:
  port: 8109

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
spring:
  application:
    name: blockchain-server
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    ## 设置字段格式化
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  # 设置数据库
  datasource:
    username: hive
    password: hivehive
    url: jdbc:mysql://10.1.1.214:3306/fs_order?useUnicode=true&characterEncoding=utf-8
    druid:
      initialSize: 2
      # druid 与 spring集成 (spring监控)
      aop-patterns: com.heyi
      filter:
        slf4j:
          enabled: true
          statement-create-after-log-enabled: false
          statement-close-after-log-enabled: false
          result-set-open-after-log-enabled: false
          result-set-close-after-log-enabled: false

      #监控控制台配置
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: 111111
        reset-enable: true
  profiles:
    active: cluster