server:
  port: 8103

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
    enabled: false

spring:
  # dev/prod environment config
  profiles:
    active: cluster
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    ## 设置字段格式化
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  application:
    name: filesystem
  # 设置上传文件的大小限制
  servlet:
    multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb
  # 设置静态资源路径，多个以逗号分隔
  # resources:
    # static-locations: file:///D:/Dev/GitRepository/java/blockchain-filesystem-webapp/build
  # 设置数据库
  datasource:
    username: hive
    password: hivehive
    url: jdbc:mysql://10.1.1.214:3306/fs_node1?useUnicode=true&characterEncoding=utf-8
    druid:
      initialSize: 2
      # druid 与 spring集成 (spring监控)
      aop-patterns: com.heyi
      filter:
        slf4j:
          enabled: true
          statement-create-after-log-enabled: false
          statement-close-after-log-enabled: false
          result-set-open-after-log-enabled: false
          result-set-close-after-log-enabled: false
      #监控控制台配置
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: 111111
        reset-enable: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
# swagger
springfox.documentation.swagger.v2.path: /api-docs



