swagger:
  enable: false

spring:
  resources:
    static-locations: file:///D:/temp/blockchain/web
  datasource:
    username: hive
    password: hivehive
    url: jdbc:mysql://10.1.1.214:3306/fs_node1?useUnicode=true&characterEncoding=utf-8


  mvc:
    view:
      prefix: /
      suffix: .html

  thymeleaf:
    cache: false

# 文件的保存路径
app:
  file:
    rootPath: D:/blockchain/files
  # 排序节点及当前节点的外网可达域名及端口
  endpoints:
    # order web服务
    order: 127.0.0.1
    # 本地 web 服务
    local: 127.0.0.1
  ports:
    # 区块链服务端口
    blockchain: 8109
    # 文件服务端口
    file: 8103
